### ISSUE TITLE
Pages need descriptive titles within <title> tag

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#144]
Currently the <title> content is simply "Document". We need to provide descriptive titles.

For the product listing page, follow the pattern "The Accessible eStore", [category name], [subcategory name], e.g.
"The Accessible eStore, Women, Women's Tops"

For the product details page, follow the pattern "The Accessible eStore", [category name], [subcategory name], [product name], e.g.
"The Accessible eStore, Women, Women's Tops, Long Sleeved Wrap Top"

**Comment by brianelton** [comment]
Fixed on public site
