### ISSUE TITLE
Showing products X of Y information needs aria-live attribute

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#148]
On the product listing page, the "Showing products X of Y" content updates when a filter is selected. This element needs an aria-live attribute so that the content update is announced. E.g.

`<span class="sort__showing-count" data-template="showing-count" aria-live="polite">Showing 1 <span class="element-invisible">to</span><span aria-hidden="true">-</span> 12 of 13 <span class="element-invisible">products</span></span>`

**Comment by brianelton** [comment]
Fixed on public site
