### ISSUE TITLE
Give remove filter buttons more descriptive labels

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#150]
On the product listing page, the buttons to remove the various filters are not descriptive enough. They only say the name of the filter applied and "button". Make them follow this pattern: "[filter name] + remove filter". E.g. you could do it like this, where hiddenText is hidden with CSS but available to the screen reader:

```
<h3 class="hiddenText" id="myStatement">Remove filter</h3>
<ul class="active filters">
<li class="active-filter">
      <button class="active-filter__remove-btn" data-remove-filter="blue" aria-describedby="myStatement">
        <svg class="icon--close-btn"><use xlink:href="../sprite.svg#close"></use></svg> Blue
      </button>
    </li>...
```

**Comment by brianelton** [comment]
confirmed on prod
