### ISSUE TITLE
Fix automated tool issues for PLP: Empty buttons, broken skip links

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#153]
Fix automated tool errors on the PLP. You can see the errors if you download the WAVE plugin: https://wave.webaim.org/extension/

For this ticket, please fix:
- 4 x empty button (one is for the search button in a separate ticket, one is for the close button on the mini-cart, 2 are for the carousel arrows. Give the mini-cart a live text close button that is hidden with CSS. Give the carousel arrows live text labels of next/previous even though they don't get keyboard focus)
- 9 x broken skip links. I think you are fixing these anyway.

**Comment by brianelton** [comment]
Currently 0 errors on public site
