### ISSUE TITLE
skip nav toggling

### ISSUE THREAD

**Issue by karenhawkins** [PublicisSapient/accessible-ecommerce-demo#154]
When the skip nav is activated, the user is currently brought to the page content. But I think the focus should go on to our "return to navigation menu" skip link.

**Comment by aevanson** [comment]
@karenhawkins We'll have to look into this one. It _is_ actually targeting the 'Return to navigation menu' link, but depending on the browser, it won't be focused properly. In Safari (12.1), it works as expected. In Firefox...it does not. Could be related to the fact that we're trying to push focus onto an element that's hidden?

**Comment by brianelton** [comment]
confirmed on prod
