### ISSUE TITLE
Fix automated tool issues on PDP: Empty buttons, broken skip links

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#156]
Similar to issue 153.

Fix automated tool errors on the PLP. You can see the errors if you download the WAVE plugin: https://wave.webaim.org/extension/

For this ticket, please fix:

- 2 x empty button (2 are for the carousel arrows on the product thumbnails. Give the carousel arrows live text labels of next/previous even though they don't get keyboard focus). Note there are a couple other errors but you're already fixing these for issue #153.
- 1 x broken skip link. I think you are fixing these anyway.

**Comment by brianelton** [comment]
Currently 0 errors on Wave tool
