### ISSUE TITLE
Accessibility issues with product tile links on PLP

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#163]
Two issues with product tile links on PLP:
(1) Spoken label must start with same text as visible label, and
(2) Price is spoken twice

**(1) Spoken label must start with same text as visible label**
According to guideline 2.5.3, Label in Name, we must begin any spoken label with the same text that is shown in the visible label. Currently our product tile spoken labels are formed like this:

"Learn more about" + [product name] + [price] 
whereas the visible label is:
[product name] + [price]

We should change the spoken label structure to start with the visible label. I suggest:

[Product name] + [price] + "Product details"

**(2) Price is spoken twice.**
The price is read twice for product tile links on the PLP because the aria-label contains the same price information that is already included in the link label:

```
<a class="product-tile__link" href="../pdp/index.html?product_id=37">
    ...
    <p class="product-tile__product-name" aria-label="learn more about: Long Sleeved T-Shirt, 34.99">Long Sleeved T-Shirt</p>
    <span class="product-tile__price">$34.99</span>
  </a>
```

Assuming the aria-label is programmatically generated, fix both of these by adding the aria-label to the link tag instead of to the `<p>` tag, and include the new link content structure mentioned above, so that the resulting aria-label will look like this:

`<a class="product-tile__link" href="../pdp/index.html?product_id=37" aria-label="[product name], [product price], product details">`

- Make sure the price includes the dollar sign: $34.99.
- Retain the commas between items as shown.

**Comment by brianelton** [comment]
Fixed on public site
