### ISSUE TITLE
Add form validation to Price Filters

### ISSUE THREAD

**Issue by aevanson** [PublicisSapient/accessible-ecommerce-demo#178]
Use default for from and to (0 and 999) in the event of an empty field
add some basic form validation for non-numbers

**Comment by liskulic** [comment]
@aevanson, @brianelton, is there a reason why the <input> element is not set as type "number" and min and max attributes not used?

**Comment by brianelton** [comment]
@liskulic yes, I think there is a desire to avoid having the screen reader read out "spinner" or whatever nonsense they say when it's a number input.

**Comment by liskulic** [comment]
Thanks, @brianelton. I'm working on a javascript solution right now.

**Comment by brianelton** [comment]
confirmed on prod
