### ISSUE TITLE
Add legal copy to footer (on all pages)

### ISSUE THREAD

**Issue by aevanson** [PublicisSapient/accessible-ecommerce-demo#191]
I have this disclaimer from legal that needs to be on every page. Can you find a way to get this into the footer? It should be on all pages:
 
“Publicis Sapient makes no representations or warranties about the content provided on this page. Publicis Sapient does not intend for the prototype or any other information contained on this page to constitute legal advice, nor is this content meant to capture a one-size-fits-all solution to accessibility concerns. Readers of this content should contact independent legal counsel to obtain advice with respect to any particular legal matter, including but not limited to accessibility.

**Comment by brianelton** [comment]
confirmed on prod
