### ISSUE TITLE
About page needs final statement that explains how to start using the demo

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#198]
At the end of the body of text, add this line:

To start using the prototype, navigate to the "Women" section using the global navigation menu, or -follow this link to the Women's section-. (link text denoted by dashes, should be underlined).

**Comment by alisonrae** [comment]
At the end of the body of text, add this line:

To start using the prototype, navigate to the "Women" section using the global navigation menu, or -follow this link to the Women's section-.

**Comment by brianelton** [comment]
confirmed on prod
