### ISSUE TITLE
PDP Link label issues

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#200]
On PDP, 
- change first "Read More" link to say "Full Product Description"
- Change "View ratings and reviews" to just "Ratings and reviews" (remove reference to viewing).
- Change "View size chart" to just "Size chart"
- Save to wishlist button announces "save to wishlistsave". It should say "save to wish list"

**Comment by brianelton** [comment]
confirmed on prod
