### ISSUE TITLE
Empty button on close button on the modal to say functionality is not done yet

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#208]
Please do a WAVE test, you will see the empty button error. I believe it is for the close button on the "functionality is not ready yet" modal. Can this be fixed today? :-)

**Comment by alisonrae** [comment]
I saw this on the About page.

**Comment by brianelton** [comment]
I ran the Wave tool on PLP and PDP on Monday and they both came back clean. I also know that the close button on the construction modal has live text in a "sr-only" span. I will look into it.

**Comment by brianelton** [comment]
Wave tool showing 0 errors
