### ISSUE TITLE
Update contributors/our team on About us

### ISSUE THREAD

**Issue by aevanson** [PublicisSapient/accessible-ecommerce-demo#211]
Here's a list of all the people who have contributed to making the eStore, well, most anyway. Please see the attached excel. I think we need to add a few people, like Brian and Wes and Lisa and any other recent folks (can someone do this please?).
 
Since we are not having a team photo for launch, Alison and I think it’d be good to just list all the contributors in alphabetical order without any roles (jobs) associated. If you can make a few columns, that’d be great.

[eStore Contributors.xlsx](https://github.com/PublicisSapient/accessible-ecommerce-demo/files/3182704/eStore.Contributors.xlsx)

**Comment by brianelton** [comment]
Confirmed on prod.
