### ISSUE TITLE
Update images for gallery

### ISSUE THREAD

**Issue by brianelton** [PublicisSapient/accessible-ecommerce-demo#215]
https://lion.app.box.com/folder/71594861716

**Comment by aevanson** [comment]
Assets zip added. 

*t-shirt*: images can be added for PLP and first 'featured' image on PDP
*top*: images can be used for supplemental images on PDP (same for every page...hardcoded)

[_Assets.zip](https://github.com/PublicisSapient/accessible-ecommerce-demo/files/3183713/_Assets.zip)

**Comment by brianelton** [comment]
Images need to be optimized, but they are there on prod
