### ISSUE TITLE
Images not showing up on PLP

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#235]
Just as an FYI -- not sure why the images aren't showing up. I notice they are from the placeholder image site. They don't say that the service is down or anything.

**Comment by aevanson** [comment]
@alisonrae this may be a caching issue. We've replaced all of the old placeholder images with ones that are in our own repository. Please clear all of you caches and try again.

**Comment by aevanson** [comment]
Closing this because I think it was just a caching issue.
