### ISSUE TITLE
Accessible estore title change for better pronunciation

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#244]
Currently we refer to the "accessible estore" in the title tag. Let's change that to

The Accessible E Store 

So the screen reader will always pronounce it right. For me, currently voiceover says "the accessible "eh" store. If possible it would also be great to get an "accessible e store" aria-label wherever it is mentioned in the text. Note, I do not want to change the name visually, just for pronunciation.

**Comment by liskulic** [comment]
This is done, closing ticket.
