### ISSUE TITLE
The cart label says 3 items, but the screen reader announces 2 items

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#263]
Steps to reproduce: Add an item to the cart. The cart will be updated accordingly with the number of items. Tab over to the cart. Listen to the screen reader announce the number of items. When I did it, although my cart had 3 items, the screen reader read that the cart had 2 items.

<button aria-label="Mini Cart, 2 items, estimated subtotal: $42.92" data-js="mini-cart-toggle" class="secondary-nav__button" aria-haspopup="true" aria-expanded="false">

The screen reader is announcing the aria-label. Looks like that is not getting updated with the number of items in the cart.

**Comment by liskulic** [comment]
Bug fixed and updated the aria-label for each of the product item <a> elements in mini cart. Also added aria-labels to the Remove button, Edit link, and Save to List button for each product in the mini cart.

Awaiting PR approval and merge.
