### ISSUE TITLE
Bypass block link labels for skipping navigation need to be more descriptive

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#35]
Currently the bypass block links are:

(1) "Skip to main content" --> (skips navigation)
`<nav>...</nav>`
(2) "Skip to nav" --> (returns to the skip navigation link)

Ideas:
(1) The link isn't really skipping directly to the main content in this case. Please change to "Skip navigation menu".
(2) "Skip to nav" is really jargon of our field. Suggest it be changed to something like, "Return to navigation menu".

**Comment by mikequattrin** [comment]
Fix has been applied for this issue. Closing.
