### ISSUE TITLE
Use of HTML5 section element for navigation when there is a more semantic alternative

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#36]
The global navigation is marked up as a <section> element. It is more semantic to use the <nav> element for navigation. 

Use the nav element with aria-label="Primary navigation" for the global nav instead of a section.

**Comment by alisonrae** [comment]
Hi Mike, I think navigation should at least enclose the logo, because that is how people can get back home. I'd probably err on the side of including the whole top navigation including the cart.

**Comment by mikequattrin** [comment]
Hi Alison,

Thank you for the feedback and guidance. I have converted the section to a nav and opened up a pull request. 

-Mike

**Comment by mikequattrin** [comment]
Pull request has been merged. Navigation now correctly marked via a nav element. Closing.
