### ISSUE TITLE
Label for email field is not informative

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#42]
According to WCAG 2.4.6, field labels must be informative.

Currently, the label is "subscribe to our newsletter" which is not informative enough because it is not telling me to enter my email address. I know there is placeholder text but that does not replace a label.

Please make the "Subscribe to our Newsletter" some kind of heading, and make the label "enter email address".

**Comment by mikequattrin** [comment]
Fixed as part of defect #41 [(Via this PR)](https://github.com/PublicisSapient/accessible-ecommerce-demo/pull/51). Marking as closed. Excellent work, Alan!
