### ISSUE TITLE
Minicart needs visible information to match information provided to screen reader user

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#44]
Currently the mini cart icon is just a cart, even if there are items in the cart. Meanwhile, a screen reader user will hear a subtotal and the number of items in the cart.

Please display the subtotal and the number of items in the cart visually. Please do this however you like and a designer can review it later.

**Comment by zoltan-dulac** [comment]
Made PR for fix.
