### ISSUE TITLE
Carousel functionality isn't working and isn't accessible

### ISSUE THREAD

**Issue by aevanson** [PublicisSapient/accessible-ecommerce-demo#52]
When additional items are added to the product carousel, they are forcing the existing elements to get squished.

The previous/next buttons need better enable/disable and scroll min/max functionality. Currently the carousel will scroll to an empty 'page' with no items visible.

The jump links before and after the carousel aren't showing up on focus.

**Comment by alisonrae** [comment]
Hi Alan, Can you add more than 4 items to the carousel so that I can test it? Thanks!

**Comment by aevanson** [comment]
Hi @alisonrae, I had already added more cards as part of my changes. The 'live' link doesn't have the latest code from `dev`. I believe you'll have to pull the latest `dev` branch and test locally.
