### ISSUE TITLE
onBlur out of the mini-cart dropdown it should disappear.

### ISSUE THREAD

**Issue by zoltan-dulac** [PublicisSapient/accessible-ecommerce-demo#60]
When the mini-cart is standalone, the dropdown menu disappears when the user tabs out of it.  This was by design.  This functionality didn't work when integrated into the site.  I *think* this should be fixed, but I want to confirm with @alisonrae about this.

If this is the desired behaviour, there is a branch that does fix this issue:

https://github.com/PublicisSapient/accessible-ecommerce-demo/tree/defect/fix-on-blur-out-of-dropdown-it-does-not-disappear

Please let me know if this is the desired behaviour and I will create a PR for it.

**Comment by alisonrae** [comment]
This functionality is correct. Thanks, Z!
