### ISSUE TITLE
Differentiate product properties and enable sorting/filtering

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#76]
Expected behavior: Products in the product grid should have different properties, including different prices, colors, and brands.
Actual behavior: All products have the same price, and color and brand are not mentioned in the product name.

Expected behavior: Filtering and sorting actions should be functional.
Actual behavior: Filtering and sorting actions don't appear to do anything on the product grid.

**Comment by aevanson** [comment]
Closing. Issue is no longer valid
