### ISSUE TITLE
Screen reader item count inaccurate for list of footer links.

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#93]
Unordered list with non-**li** items in it in footer renders screen reader item count inaccurate.

**Expected behavior:** When I have my screen reader on and tab to the first link in the list of footer links, the screen reader should read the link label, identify the link as being part of an unordered list, and say how many items are in that list. In this case, it should say, "About, list 8 items."

**Actual behavior:** The screen reader says, "About, list 10 items, 1 sublist." It says that, because there are additional elements in the list.

E.g. there is a hidden **h3** element that is counted (but not read by the screen reader). And the 10th item is actually the sublist.

People use that count to orient themselves to content. We can make the count correct by not marking up a list with additional elements inside it. Please mark up the list as a single list with only li elements as children of the ul so that the count is accurate.

**Comment by aevanson** [comment]
Closing. Issue no longer valid.
