### ISSUE TITLE
PDP | Visual issues

### ISSUE THREAD

**Issue by roseyxli** [PublicisSapient/accessible-ecommerce-demo#97]
Per Karen:

1. We need a page heading “Women’s Shirts and Tops”
2. I would like to make the “sort by” a dropdown
3. I don’t like how the product cards stretch so much, even on desktop. Can we make it so that they stretch to a certain point (maybe we need a VD opinion on this) and then we have gutters?
4. I think the filter should be much wider.
5. “Filters” should be an h2 but it is styled much smaller than “sort by”. So we need someone to look at the heading structure and styles.
6. I don’t link how there is no padding to the left and right, especially around the carousel.
7. The carousel isn’t quite right. I can make my screen width larger and smaller but the carousel doesn’t respond as I expect.

**Comment by aevanson** [comment]
Closing issue. Out of date based on new designs/requirements.
